FROM python:3.14-slim

WORKDIR /opt

# Копируем requirements.txt из корня (он рядом с Dockerfile)
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем всю папку app в /opt/app
COPY app/ /opt/app/

# Устанавливаем PYTHONPATH, чтобы Python видел пакет app
ENV PYTHONPATH=/opt

# Запускаем модуль app.main
CMD ["python", "-m", "app.main"]
