FROM debezium/connect:2.6

USER root

# Папка для JDBC коннектора
ENV JDBC_DIR=/kafka/connect/kafka-connect-jdbc
RUN mkdir -p ${JDBC_DIR}

# Core JDBC connector
RUN curl -sLf -o ${JDBC_DIR}/kafka-connect-jdbc-10.7.4.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/10.7.4/kafka-connect-jdbc-10.7.4.jar

# Required dependencies
RUN curl -sLf -o ${JDBC_DIR}/common-utils-7.6.0.jar \
    https://packages.confluent.io/maven/io/confluent/common-utils/7.6.0/common-utils-7.6.0.jar && \
    curl -sLf -o ${JDBC_DIR}/common-config-7.6.0.jar \
    https://packages.confluent.io/maven/io/confluent/common-config/7.6.0/common-config-7.6.0.jar && \
    curl -sLf -o ${JDBC_DIR}/kafka-connect-avro-converter-7.6.0.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/7.6.0/kafka-connect-avro-converter-7.6.0.jar && \
    curl -sLf -o ${JDBC_DIR}/kafka-avro-serializer-7.6.0.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/7.6.0/kafka-avro-serializer-7.6.0.jar && \
    curl -sLf -o ${JDBC_DIR}/kafka-schema-registry-client-7.6.0.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.6.0/kafka-schema-registry-client-7.6.0.jar && \
    curl -sLf -o ${JDBC_DIR}/kafka-schema-serializer-7.6.0.jar \
    https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/7.6.0/kafka-schema-serializer-7.6.0.jar && \
    curl -sLf -o ${JDBC_DIR}/avro-1.11.3.jar \
    https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.3/avro-1.11.3.jar && \
    curl -sLf -o ${JDBC_DIR}/sqlite-jdbc-3.42.0.0.jar \
    https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.42.0.0/sqlite-jdbc-3.42.0.0.jar && \
    curl -sLf -o ${JDBC_DIR}/jtds-1.3.1.jar \
    https://repo1.maven.org/maven2/net/sourceforge/jtds/jtds/1.3.1/jtds-1.3.1.jar

# ClickHouse JDBC driver (shaded, includes all dependencies)
RUN curl -sLf -o ${JDBC_DIR}/clickhouse-jdbc-shaded.jar \
    https://github.com/ClickHouse/clickhouse-java/releases/download/v0.6.3/clickhouse-jdbc-0.6.3-shaded.jar

USER kafka
